# Generated by Django 2.2.16 on 2021-03-18 08:39

import app.validators
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='city_name')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10, null=True, validators=[app.validators.validate_number])),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='country_name')),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='ProgramsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='program_name')),
                ('duration', models.IntegerField()),
                ('requirement_1', models.CharField(max_length=200)),
                ('requirement_2', models.CharField(max_length=200)),
                ('requirement_3', models.CharField(max_length=200)),
                ('requirement_4', models.CharField(max_length=200)),
                ('requirement_5', models.CharField(max_length=200)),
                ('requirement_6', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='subject_name')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='university_name')),
                ('cover_photo', models.ImageField(upload_to='covers/')),
                ('uni_logo', models.ImageField(upload_to='covers/')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='uni_short_description')),
                ('fee', models.IntegerField()),
                ('desc_1', ckeditor.fields.RichTextField(verbose_name='uni_long_paragraph_description')),
                ('summer_intake_date', models.DateField(blank=True, null=True)),
                ('winter_intake_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'universities',
            },
        ),
        migrations.CreateModel(
            name='FilterForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cities')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Countries')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProgramsType')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.University')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10, null=True, validators=[app.validators.validate_number])),
                ('files', models.FileField(upload_to='covers/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.University')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProgramsType')),
            ],
        ),
    ]
