# Generated by Django 3.2.8 on 2021-11-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterform',
            name='fee',
            field=models.CharField(blank=True, default='N/A', max_length=10, null=True),
        ),
    ]
