# Generated by Django 3.2.8 on 2021-10-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstype',
            name='requirement_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programstype',
            name='requirement_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
