# Generated by Django 3.2.8 on 2021-10-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211007_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstype',
            name='requirement_6',
        ),
        migrations.AlterField(
            model_name='programstype',
            name='requirement_5',
            field=models.CharField(default=2020, max_length=200),
            preserve_default=False,
        ),
    ]
