# Generated by Django 3.2.8 on 2021-11-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_filterform_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
