# Generated by Django 3.2.8 on 2021-10-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211007_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackByStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('feedback', models.TextField(max_length=35)),
                ('image', models.ImageField(upload_to='covers/feedback/')),
            ],
        ),
    ]
