# Generated by Django 3.2.8 on 2021-10-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feedbackbystudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackbystudent',
            name='feedback',
            field=models.TextField(max_length=100),
        ),
    ]
