# Generated by Django 3.2.8 on 2021-11-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_university_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterform',
            name='duration',
            field=models.CharField(max_length=4),
        ),
    ]
