# Generated by Django 3.2.8 on 2021-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_feedbackbystudent_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='cover_photo',
            field=models.ImageField(upload_to='covers/uni_cover_photo/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='uni_logo',
            field=models.ImageField(upload_to='covers/uni_logo/'),
        ),
    ]
