# Generated by Django 3.2.8 on 2021-11-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_filterform_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special', models.BooleanField(default=True, unique=True)),
                ('moto', models.CharField(max_length=100, verbose_name='company_moto')),
                ('heading_title', models.CharField(max_length=100, verbose_name='Heading_title')),
                ('button_name1', models.CharField(max_length=100, verbose_name='study_program_button')),
                ('button_name2', models.CharField(max_length=100, verbose_name='study_program_button')),
                ('apply_online_title', models.CharField(max_length=100, verbose_name='Apply_online_title')),
                ('apply_online_desc', models.CharField(max_length=100, verbose_name='Apply_online_desc')),
                ('apply_online_button_name', models.CharField(max_length=100, verbose_name='Apply_online_button_name')),
                ('contact_us_title', models.CharField(max_length=100, verbose_name='contact_us_title')),
                ('contact_us_desc', models.CharField(max_length=100, verbose_name='contact_us_desc')),
                ('contact_us_button_name', models.CharField(max_length=100, verbose_name='contact_us_button_name')),
                ('feature_title', models.CharField(max_length=100, verbose_name='Feature_title')),
                ('feature_heading_title', models.CharField(max_length=100, verbose_name='Feature_heading_title')),
                ('Stats_title', models.CharField(max_length=100, verbose_name='Stats_Title')),
                ('Article_title', models.CharField(max_length=100, verbose_name='Articles_by_Students_title')),
            ],
        ),
    ]
