# Generated by Django 3.2.8 on 2021-10-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211008_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='files',
            field=models.FileField(upload_to='covers/application_file/'),
        ),
    ]
