# Generated by Django 3.2.8 on 2021-11-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_homepageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageinfo',
            name='heading_first_image',
            field=models.ImageField(default=2020, upload_to='covers/homepage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepageinfo',
            name='heading_second_image',
            field=models.ImageField(default=2020, upload_to='covers/homepage/'),
            preserve_default=False,
        ),
    ]
