# Generated by Django 3.2.8 on 2021-11-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211110_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageinfo',
            old_name='Article_title',
            new_name='article_title',
        ),
        migrations.RenameField(
            model_name='homepageinfo',
            old_name='Stats_title',
            new_name='stats_title',
        ),
    ]
