# Generated by Django 3.2.8 on 2021-10-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_applicationform_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackbystudent',
            name='show_this',
            field=models.BooleanField(default=True),
        ),
    ]
