# Generated by Django 3.2.8 on 2021-10-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_feedbackbystudent_show_this'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
