# Generated by Django 3.2.8 on 2021-10-11 08:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_university_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='consultancy_name')),
                ('logo_photo', models.ImageField(upload_to='covers/consultancy/')),
                ('desc', ckeditor.fields.RichTextField(max_length=200)),
                ('special', models.BooleanField(default=False)),
            ],
        ),
    ]
