# Generated by Django 3.2.8 on 2021-11-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_homepageinfo_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterform',
            name='duration',
            field=models.CharField(max_length=6, verbose_name='Duration: Eg. 2 or 2.5 '),
        ),
        migrations.AlterField(
            model_name='filterform',
            name='fee',
            field=models.CharField(default='N/A', max_length=10, verbose_name='Fee: Write with Rs or $ before actual Fee'),
        ),
        migrations.AlterUniqueTogether(
            name='filterform',
            unique_together={('university', 'program')},
        ),
    ]
