# Generated by Django 3.2.8 on 2021-10-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_consultancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultancy',
            options={'verbose_name_plural': 'consultancies'},
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='desc',
            field=models.TextField(max_length=100, verbose_name='uni_short_description'),
        ),
    ]
