# Generated by Django 3.2.8 on 2021-10-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211030_0635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialLinks',
            new_name='SocialLink',
        ),
    ]
