# Generated by Django 3.2.8 on 2021-10-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_sociallinks_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='email_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='fb_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
