# Generated by Django 3.2.8 on 2021-10-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211030_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='special',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
