# Generated by Django 3.2.8 on 2021-10-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_sociallink_special'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
