# Generated by Django 3.2.8 on 2021-10-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_announcement_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='show_this',
            field=models.BooleanField(default=True),
        ),
    ]
