# Generated by Django 3.2.7 on 2021-10-23 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_announcement_show_this'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2021, 10, 23)),
        ),
    ]
