# Generated by Django 3.2.8 on 2021-10-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_aboutdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdesc',
            name='special',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
